<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            [
                'name'      =>  'Afghanistan',
                'iso_code2' =>  'AF',
                'iso_code3' =>  'AFG',
                'numeric'   => '004',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Albania',
                'iso_code2' =>  'AL',
                'iso_code3' =>  'ALB',
                'numeric'   => '008',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Algeria',
                'iso_code2' =>  'DZ',
                'iso_code3' =>  'DZA',
                'numeric'   => '012',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'American Samoa',
                'iso_code2' =>  'AS',
                'iso_code3' =>  'ASM',
                'numeric'   => '016',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Andorra',
                'iso_code2' =>  'AD',
                'iso_code3' =>  'AND',
                'numeric'   => '020',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Angola',
                'iso_code2' =>  'AO',
                'iso_code3' =>  'AGO',
                'numeric'   => '024',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Anguilla',
                'iso_code2' =>  'AI',
                'iso_code3' =>  'AIA',
                'numeric'   => '660',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Antarctica',
                'iso_code2' =>  'AQ',
                'iso_code3' =>  'ATA',
                'numeric'   => '010',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Antigua and Barbuda',
                'iso_code2' =>  'AG',
                'iso_code3' =>  'ATG',
                'numeric'   => '028',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Argentina',
                'iso_code2' =>  'AR',
                'iso_code3' =>  'ARG',
                'numeric'   => '032',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Armenia',
                'iso_code2' =>  'AM',
                'iso_code3' =>  'ARM',
                'numeric'   => '051',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Aruba',
                'iso_code2' =>  'AW',
                'iso_code3' =>  'ABW',
                'numeric'   => '533',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Australia',
                'iso_code2' =>  'AU',
                'iso_code3' =>  'AUS',
                'numeric'   => '036',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Austria',
                'iso_code2' =>  'AT',
                'iso_code3' =>  'AUT',
                'numeric'   => '040',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Azerbaijan',
                'iso_code2' =>  'AZ',
                'iso_code3' =>  'AZE',
                'numeric'   => '031',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bahamas (the)',
                'iso_code2' =>  'BS',
                'iso_code3' =>  'BHS',
                'numeric'   => '044',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bahrain',
                'iso_code2' =>  'BH',
                'iso_code3' =>  'BHR',
                'numeric'   => '048',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bangladesh',
                'iso_code2' =>  'BD',
                'iso_code3' =>  'BGD',
                'numeric'   => '050',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Barbados',
                'iso_code2' =>  'BB',
                'iso_code3' =>  'BRB',
                'numeric'   => '052',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Belarus',
                'iso_code2' =>  'BY',
                'iso_code3' =>  'BLR',
                'numeric'   => '112',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Belgium',
                'iso_code2' =>  'BE',
                'iso_code3' =>  'BEL',
                'numeric'   => '056',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Belize',
                'iso_code2' =>  'BZ',
                'iso_code3' =>  'BLZ',
                'numeric'   => '084',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Benin',
                'iso_code2' =>  'BJ',
                'iso_code3' =>  'BEN',
                'numeric'   => '204',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bermuda',
                'iso_code2' =>  'BM',
                'iso_code3' =>  'BMU',
                'numeric'   => '060',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bhutan',
                'iso_code2' =>  'BT',
                'iso_code3' =>  'BTN',
                'numeric'   => '064',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bolivia (Plurinational State of)',
                'iso_code2' =>  'BO',
                'iso_code3' =>  'BOL',
                'numeric'   => '068',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bonaire, Sint Eustatius and Saba',
                'iso_code2' =>  'BQ',
                'iso_code3' =>  'BES',
                'numeric'   => '535',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bosnia and Herzegovina',
                'iso_code2' =>  'BA',
                'iso_code3' =>  'BIH',
                'numeric'   => '070',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Botswana',
                'iso_code2' =>  'BW',
                'iso_code3' =>  'BWA',
                'numeric'   => '072',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bouvet Island',
                'iso_code2' =>  'BV',
                'iso_code3' =>  'BVT',
                'numeric'   => '074',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Brazil',
                'iso_code2' =>  'BR',
                'iso_code3' =>  'BRA',
                'numeric'   => '076',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'British Indian Ocean Territory (the)',
                'iso_code2' =>  'IO',
                'iso_code3' =>  'IOT',
                'numeric'   => '086',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Brunei Darussalam',
                'iso_code2' =>  'BN',
                'iso_code3' =>  'BRN',
                'numeric'   => '096',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Bulgaria',
                'iso_code2' =>  'BG',
                'iso_code3' =>  'BGR',
                'numeric'   => '100',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Burkina Faso',
                'iso_code2' =>  'BF',
                'iso_code3' =>  'BFA',
                'numeric'   => '854',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Burundi',
                'iso_code2' =>  'BI',
                'iso_code3' =>  'BDI',
                'numeric'   => '108',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cabo Verde',
                'iso_code2' =>  'CV',
                'iso_code3' =>  'CPV',
                'numeric'   => '132',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cambodia',
                'iso_code2' =>  'KH',
                'iso_code3' =>  'KHM',
                'numeric'   => '116',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cameroon',
                'iso_code2' =>  'CM',
                'iso_code3' =>  'CMR',
                'numeric'   => '120',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Canada',
                'iso_code2' =>  'CA',
                'iso_code3' =>  'CAN',
                'numeric'   => '124',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cayman Islands (the)',
                'iso_code2' =>  'KY',
                'iso_code3' =>  'CYM',
                'numeric'   => '136',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Central African Republic (the)',
                'iso_code2' =>  'CF',
                'iso_code3' =>  'CAF',
                'numeric'   => '140',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Chad',
                'iso_code2' =>  'TD',
                'iso_code3' =>  'TCD',
                'numeric'   => '148',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Chile',
                'iso_code2' =>  'CL',
                'iso_code3' =>  'CHL',
                'numeric'   => '152',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'China',
                'iso_code2' =>  'CN',
                'iso_code3' =>  'CHN',
                'numeric'   => '156',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Christmas Island',
                'iso_code2' =>  'CX',
                'iso_code3' =>  'CXR',
                'numeric'   => '162',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cocos (Keeling) Islands (the)',
                'iso_code2' =>  'CC',
                'iso_code3' =>  'CCK',
                'numeric'   => '166',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Colombia',
                'iso_code2' =>  'CO',
                'iso_code3' =>  'COL',
                'numeric'   => '170',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Comoros (the)',
                'iso_code2' =>  'KM',
                'iso_code3' =>  'COM',
                'numeric'   => '174',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Congo (the Democratic Republic of the)',
                'iso_code2' =>  'CD',
                'iso_code3' =>  'COD',
                'numeric'   => '180',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Congo (the)',
                'iso_code2' =>  'CG',
                'iso_code3' =>  'COG',
                'numeric'   => '178',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cook Islands (the)',
                'iso_code2' =>  'CK',
                'iso_code3' =>  'COK',
                'numeric'   => '184',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Costa Rica',
                'iso_code2' =>  'CR',
                'iso_code3' =>  'CRI',
                'numeric'   => '188',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Croatia',
                'iso_code2' =>  'HR',
                'iso_code3' =>  'HRV',
                'numeric'   => '191',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cuba',
                'iso_code2' =>  'CU',
                'iso_code3' =>  'CUB',
                'numeric'   => '192',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Curaçao',
                'iso_code2' =>  'CW',
                'iso_code3' =>  'CUW',
                'numeric'   => '531',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Cyprus',
                'iso_code2' =>  'CY',
                'iso_code3' =>  'CYP',
                'numeric'   => '196',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Czechia',
                'iso_code2' =>  'CZ',
                'iso_code3' =>  'CZE',
                'numeric'   => '203',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  "Côte d'Ivoire",
                'iso_code2' =>  'CI',
                'iso_code3' =>  'CIV',
                'numeric'   => '384',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Denmark',
                'iso_code2' =>  'DK',
                'iso_code3' =>  'DNK',
                'numeric'   => '208',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Djibouti',
                'iso_code2' =>  'DJ',
                'iso_code3' =>  'DJI',
                'numeric'   => '262',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Dominica',
                'iso_code2' =>  'DM',
                'iso_code3' =>  'DMA',
                'numeric'   => '212',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Dominican Republic (the)',
                'iso_code2' =>  'DO',
                'iso_code3' =>  'DOM',
                'numeric'   => '214',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Ecuador',
                'iso_code2' =>  'EC',
                'iso_code3' =>  'ECU',
                'numeric'   => '218',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Egypt',
                'iso_code2' =>  'EG',
                'iso_code3' =>  'EGY',
                'numeric'   => '818',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'El Salvador',
                'iso_code2' =>  'SV',
                'iso_code3' =>  'SLV',
                'numeric'   => '222',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Equatorial Guinea',
                'iso_code2' =>  'GQ',
                'iso_code3' =>  'GNQ',
                'numeric'   => '226',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Eritrea',
                'iso_code2' =>  'ER',
                'iso_code3' =>  'ERI',
                'numeric'   => '232',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Estonia',
                'iso_code2' =>  'EE',
                'iso_code3' =>  'EST',
                'numeric'   => '233',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Eswatini',
                'iso_code2' =>  'SZ',
                'iso_code3' =>  'SWZ',
                'numeric'   => '748',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Ethiopia',
                'iso_code2' =>  'ET',
                'iso_code3' =>  'ETH',
                'numeric'   => '231',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Falkland Islands (the) [Malvinas]',
                'iso_code2' =>  'FK',
                'iso_code3' =>  'FLK',
                'numeric'   => '238',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Faroe Islands (the)',
                'iso_code2' =>  'FO',
                'iso_code3' =>  'FRO',
                'numeric'   => '234',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Fiji',
                'iso_code2' =>  'FJ',
                'iso_code3' =>  'FJI',
                'numeric'   => '242',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Finland',
                'iso_code2' =>  'FI',
                'iso_code3' =>  'FIN',
                'numeric'   => '246',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'France',
                'iso_code2' =>  'FR',
                'iso_code3' =>  'FRA',
                'numeric'   => '250',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'French Guiana',
                'iso_code2' =>  'GF',
                'iso_code3' =>  'GUF',
                'numeric'   => '254',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'French Polynesia',
                'iso_code2' =>  'PF',
                'iso_code3' =>  'PYF',
                'numeric'   => '258',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'French Southern Territories (the)',
                'iso_code2' =>  'TF',
                'iso_code3' =>  'ATF',
                'numeric'   => '260',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Gabon',
                'iso_code2' =>  'GA',
                'iso_code3' =>  'GAB',
                'numeric'   => '266',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Gambia (the)',
                'iso_code2' =>  'GM',
                'iso_code3' =>  'GMB',
                'numeric'   => '270',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Georgia',
                'iso_code2' =>  'GE',
                'iso_code3' =>  'GEO',
                'numeric'   => '268',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Germany',
                'iso_code2' =>  'DE',
                'iso_code3' =>  'DEU',
                'numeric'   => '276',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Ghana',
                'iso_code2' =>  'GH',
                'iso_code3' =>  'GHA',
                'numeric'   => '288',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Gibraltar',
                'iso_code2' =>  'GI',
                'iso_code3' =>  'GIB',
                'numeric'   => '292',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Greece',
                'iso_code2' =>  'GR',
                'iso_code3' =>  'GRC',
                'numeric'   => '300',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Greenland',
                'iso_code2' =>  'GL',
                'iso_code3' =>  'GRL',
                'numeric'   => '304',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Grenada',
                'iso_code2' =>  'GD',
                'iso_code3' =>  'GRD',
                'numeric'   => '308',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guadeloupe',
                'iso_code2' =>  'GP',
                'iso_code3' =>  'GLP',
                'numeric'   => '312',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guam',
                'iso_code2' =>  'GU',
                'iso_code3' =>  'GUM',
                'numeric'   => '316',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guatemala',
                'iso_code2' =>  'GT',
                'iso_code3' =>  'GTM',
                'numeric'   => '320',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guernsey',
                'iso_code2' =>  'GG',
                'iso_code3' =>  'GGY',
                'numeric'   => '831',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guinea',
                'iso_code2' =>  'GN',
                'iso_code3' =>  'GIN',
                'numeric'   => '324',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guinea-Bissau',
                'iso_code2' =>  'GW',
                'iso_code3' =>  'GNB',
                'numeric'   => '624',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Guyana',
                'iso_code2' =>  'GY',
                'iso_code3' =>  'GUY',
                'numeric'   => '328',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Haiti',
                'iso_code2' =>  'HT',
                'iso_code3' =>  'HTI',
                'numeric'   => '332',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Heard Island and McDonald Islands',
                'iso_code2' =>  'HM',
                'iso_code3' =>  'HMD',
                'numeric'   => '334',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Holy See (the)',
                'iso_code2' =>  'VA',
                'iso_code3' =>  'VAT',
                'numeric'   => '336',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Honduras',
                'iso_code2' =>  'HN',
                'iso_code3' =>  'HND',
                'numeric'   => '340',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Hong Kong',
                'iso_code2' =>  'HK',
                'iso_code3' =>  'HKG',
                'numeric'   => '344',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Hungary',
                'iso_code2' =>  'HU',
                'iso_code3' =>  'HUN',
                'numeric'   => '348',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Iceland',
                'iso_code2' =>  'IS',
                'iso_code3' =>  'ISL',
                'numeric'   => '352',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'India',
                'iso_code2' =>  'IN',
                'iso_code3' =>  'IND',
                'numeric'   => '356',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Indonesia',
                'iso_code2' =>  'ID',
                'iso_code3' =>  'IDN',
                'numeric'   => '360',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Iran (Islamic Republic of)',
                'iso_code2' =>  'IR',
                'iso_code3' =>  'IRN',
                'numeric'   => '364',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Iraq',
                'iso_code2' =>  'IQ',
                'iso_code3' =>  'IRQ',
                'numeric'   => '368',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Ireland',
                'iso_code2' =>  'IE',
                'iso_code3' =>  'IRL',
                'numeric'   => '372',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Isle of Man',
                'iso_code2' =>  'IM',
                'iso_code3' =>  'IMN',
                'numeric'   => '833',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Israel',
                'iso_code2' =>  'IL',
                'iso_code3' =>  'ISR',
                'numeric'   => '376',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Italy',
                'iso_code2' =>  'IT',
                'iso_code3' =>  'ITA',
                'numeric'   => '380',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Jamaica',
                'iso_code2' =>  'JM',
                'iso_code3' =>  'JAM',
                'numeric'   => '388',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Japan',
                'iso_code2' =>  'JP',
                'iso_code3' =>  'JPN',
                'numeric'   => '392',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Jersey',
                'iso_code2' =>  'JE',
                'iso_code3' =>  'JEY',
                'numeric'   => '832',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Jordan',
                'iso_code2' =>  'JO',
                'iso_code3' =>  'JOR',
                'numeric'   => '400',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Kazakhstan',
                'iso_code2' =>  'KZ',
                'iso_code3' =>  'KAZ',
                'numeric'   => '398',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Kenya',
                'iso_code2' =>  'KE',
                'iso_code3' =>  'KEN',
                'numeric'   => '404',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Kiribati',
                'iso_code2' =>  'KI',
                'iso_code3' =>  'KIR',
                'numeric'   => '296',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  "Korea (the Democratic People's Republic of)",
                'iso_code2' =>  'KP',
                'iso_code3' =>  'PRK',
                'numeric'   => '408',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Korea (the Republic of)',
                'iso_code2' =>  'KR',
                'iso_code3' =>  'KOR',
                'numeric'   => '410',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Kuwait',
                'iso_code2' =>  'KW',
                'iso_code3' =>  'KWT',
                'numeric'   => '414',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Kyrgyzstan',
                'iso_code2' =>  'KG',
                'iso_code3' =>  'KGZ',
                'numeric'   => '417',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  "Lao People's Democratic Republic (the)",
                'iso_code2' =>  'LA',
                'iso_code3' =>  'LAO',
                'numeric'   => '418',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Latvia',
                'iso_code2' =>  'LV',
                'iso_code3' =>  'LVA',
                'numeric'   => '428',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Lebanon',
                'iso_code2' =>  'LB',
                'iso_code3' =>  'LBN',
                'numeric'   => '422',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Lesotho',
                'iso_code2' =>  'LS',
                'iso_code3' =>  'LSO',
                'numeric'   => '426',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Liberia',
                'iso_code2' =>  'LR',
                'iso_code3' =>  'LBR',
                'numeric'   => '430',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Libya',
                'iso_code2' =>  'LY',
                'iso_code3' =>  'LBY',
                'numeric'   => '434',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Liechtenstein',
                'iso_code2' =>  'LI',
                'iso_code3' =>  'LIE',
                'numeric'   => '438',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Lithuania',
                'iso_code2' =>  'LT',
                'iso_code3' =>  'LTU',
                'numeric'   => '440',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Luxembourg',
                'iso_code2' =>  'LU',
                'iso_code3' =>  'LUX',
                'numeric'   => '442',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Macao',
                'iso_code2' =>  'MO',
                'iso_code3' =>  'MAC',
                'numeric'   => '446',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Madagascar',
                'iso_code2' =>  'MG',
                'iso_code3' =>  'MDG',
                'numeric'   => '450',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Malawi',
                'iso_code2' =>  'MW',
                'iso_code3' =>  'MWI',
                'numeric'   => '454',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Malaysia',
                'iso_code2' =>  'MY',
                'iso_code3' =>  'MYS',
                'numeric'   => '458',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Maldives',
                'iso_code2' =>  'MV',
                'iso_code3' =>  'MDV',
                'numeric'   => '462',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mali',
                'iso_code2' =>  'ML',
                'iso_code3' =>  'MLI',
                'numeric'   => '466',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Malta',
                'iso_code2' =>  'MT',
                'iso_code3' =>  'MLT',
                'numeric'   => '470',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Marshall Islands (the)',
                'iso_code2' =>  'MH',
                'iso_code3' =>  'MHL',
                'numeric'   => '584',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Martinique',
                'iso_code2' =>  'MQ',
                'iso_code3' =>  'MTQ',
                'numeric'   => '474',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mauritania',
                'iso_code2' =>  'MR',
                'iso_code3' =>  'MRT',
                'numeric'   => '478',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mauritius',
                'iso_code2' =>  'MU',
                'iso_code3' =>  'MUS',
                'numeric'   => '480',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mayotte',
                'iso_code2' =>  'YT',
                'iso_code3' =>  'MYT',
                'numeric'   => '175',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mexico',
                'iso_code2' =>  'MX',
                'iso_code3' =>  'MEX',
                'numeric'   => '484',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Micronesia (Federated States of)',
                'iso_code2' =>  'FM',
                'iso_code3' =>  'FSM',
                'numeric'   => '583',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Moldova (the Republic of)',
                'iso_code2' =>  'MD',
                'iso_code3' =>  'MDA',
                'numeric'   => '498',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Monaco',
                'iso_code2' =>  'MC',
                'iso_code3' =>  'MCO',
                'numeric'   => '492',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mongolia',
                'iso_code2' =>  'MN',
                'iso_code3' =>  'MNG',
                'numeric'   => '496',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Montenegro',
                'iso_code2' =>  'ME',
                'iso_code3' =>  'MNE',
                'numeric'   => '499',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Montserrat',
                'iso_code2' =>  'MS',
                'iso_code3' =>  'MSR',
                'numeric'   => '500',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Morocco',
                'iso_code2' =>  'MA',
                'iso_code3' =>  'MAR',
                'numeric'   => '504',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Mozambique',
                'iso_code2' =>  'MZ',
                'iso_code3' =>  'MOZ',
                'numeric'   => '508',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Myanmar',
                'iso_code2' =>  'MM',
                'iso_code3' =>  'MMR',
                'numeric'   => '104',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Namibia',
                'iso_code2' =>  'NA',
                'iso_code3' =>  'NAM',
                'numeric'   => '516',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Nauru',
                'iso_code2' =>  'NR',
                'iso_code3' =>  'NRU',
                'numeric'   => '520',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Nepal',
                'iso_code2' =>  'NP',
                'iso_code3' =>  'NPL',
                'numeric'   => '524',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Netherlands (the)',
                'iso_code2' =>  'NL',
                'iso_code3' =>  'NLD',
                'numeric'   => '528',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'New Caledonia',
                'iso_code2' =>  'NC',
                'iso_code3' =>  'NCL',
                'numeric'   => '540',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'New Zealand',
                'iso_code2' =>  'NZ',
                'iso_code3' =>  'NZL',
                'numeric'   => '554',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Nicaragua',
                'iso_code2' =>  'NI',
                'iso_code3' =>  'NIC',
                'numeric'   => '558',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Niger (the)',
                'iso_code2' =>  'NE',
                'iso_code3' =>  'NER',
                'numeric'   => '562',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Nigeria',
                'iso_code2' =>  'NG',
                'iso_code3' =>  'NGA',
                'numeric'   => '566',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Niue',
                'iso_code2' =>  'NU',
                'iso_code3' =>  'NIU',
                'numeric'   => '570',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Norfolk Island',
                'iso_code2' =>  'NF',
                'iso_code3' =>  'NFK',
                'numeric'   => '574',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Northern Mariana Islands (the)',
                'iso_code2' =>  'MP',
                'iso_code3' =>  'MNP',
                'numeric'   => '580',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Norway',
                'iso_code2' =>  'NO',
                'iso_code3' =>  'NOR',
                'numeric'   => '578',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Oman',
                'iso_code2' =>  'OM',
                'iso_code3' =>  'OMN',
                'numeric'   => '512',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Pakistan',
                'iso_code2' =>  'PK',
                'iso_code3' =>  'PAK',
                'numeric'   => '586',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Palau',
                'iso_code2' =>  'PW',
                'iso_code3' =>  'PLW',
                'numeric'   => '585',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Palestine, State of',
                'iso_code2' =>  'PS',
                'iso_code3' =>  'PSE',
                'numeric'   => '275',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Panama',
                'iso_code2' =>  'PA',
                'iso_code3' =>  'PAN',
                'numeric'   => '591',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Papua New Guinea',
                'iso_code2' =>  'PG',
                'iso_code3' =>  'PNG',
                'numeric'   => '598',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Paraguay',
                'iso_code2' =>  'PY',
                'iso_code3' =>  'PRY',
                'numeric'   => '600',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Peru',
                'iso_code2' =>  'PE',
                'iso_code3' =>  'PER',
                'numeric'   => '604',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Philippines (the)',
                'iso_code2' =>  'PH',
                'iso_code3' =>  'PHL',
                'numeric'   => '608',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Pitcairn',
                'iso_code2' =>  'PN',
                'iso_code3' =>  'PCN',
                'numeric'   => '612',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Poland',
                'iso_code2' =>  'PL',
                'iso_code3' =>  'POL',
                'numeric'   => '616',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Portugal',
                'iso_code2' =>  'PT',
                'iso_code3' =>  'PRT',
                'numeric'   => '620',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Puerto Rico',
                'iso_code2' =>  'PR',
                'iso_code3' =>  'PRI',
                'numeric'   => '630',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Qatar',
                'iso_code2' =>  'QA',
                'iso_code3' =>  'QAT',
                'numeric'   => '634',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Republic of North Macedonia',
                'iso_code2' =>  'MK',
                'iso_code3' =>  'MKD',
                'numeric'   => '807',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Romania',
                'iso_code2' =>  'RO',
                'iso_code3' =>  'ROU',
                'numeric'   => '642',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Russian Federation (the)',
                'iso_code2' =>  'RU',
                'iso_code3' =>  'RUS',
                'numeric'   => '643',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Rwanda',
                'iso_code2' =>  'RW',
                'iso_code3' =>  'RWA',
                'numeric'   => '646',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Réunion',
                'iso_code2' =>  'RE',
                'iso_code3' =>  'REU',
                'numeric'   => '638',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Barthélemy',
                'iso_code2' =>  'BL',
                'iso_code3' =>  'BLM',
                'numeric'   => '652',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Helena, Ascension and Tristan da Cunha',
                'iso_code2' =>  'SH',
                'iso_code3' =>  'SHN',
                'numeric'   => '654',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Kitts and Nevis',
                'iso_code2' =>  'KN',
                'iso_code3' =>  'KNA',
                'numeric'   => '659',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Lucia',
                'iso_code2' =>  'LC',
                'iso_code3' =>  'LCA',
                'numeric'   => '662',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Martin (French part)',
                'iso_code2' =>  'MF',
                'iso_code3' =>  'MAF',
                'numeric'   => '663',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Pierre and Miquelon',
                'iso_code2' =>  'PM',
                'iso_code3' =>  'SPM',
                'numeric'   => '666',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saint Vincent and the Grenadines',
                'iso_code2' =>  'VC',
                'iso_code3' =>  'VCT',
                'numeric'   => '670',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Samoa',
                'iso_code2' =>  'WS',
                'iso_code3' =>  'WSM',
                'numeric'   => '882',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'San Marino',
                'iso_code2' =>  'SM',
                'iso_code3' =>  'SMR',
                'numeric'   => '674',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sao Tome and Principe',
                'iso_code2' =>  'ST',
                'iso_code3' =>  'STP',
                'numeric'   => '678',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Saudi Arabia',
                'iso_code2' =>  'SA',
                'iso_code3' =>  'SAU',
                'numeric'   => '682',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Senegal',
                'iso_code2' =>  'SN',
                'iso_code3' =>  'SEN',
                'numeric'   => '686',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Serbia',
                'iso_code2' =>  'RS',
                'iso_code3' =>  'SRB',
                'numeric'   => '688',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Seychelles',
                'iso_code2' =>  'SC',
                'iso_code3' =>  'SYC',
                'numeric'   => '690',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sierra Leone',
                'iso_code2' =>  'SL',
                'iso_code3' =>  'SLE',
                'numeric'   => '694',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Singapore',
                'iso_code2' =>  'SG',
                'iso_code3' =>  'SGP',
                'numeric'   => '702',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sint Maarten (Dutch part)',
                'iso_code2' =>  'SX',
                'iso_code3' =>  'SXM',
                'numeric'   => '534',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Slovakia',
                'iso_code2' =>  'SK',
                'iso_code3' =>  'SVK',
                'numeric'   => '703',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Slovenia',
                'iso_code2' =>  'SI',
                'iso_code3' =>  'SVN',
                'numeric'   => '705',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Solomon Islands',
                'iso_code2' =>  'SB',
                'iso_code3' =>  'SLB',
                'numeric'   => '090',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Somalia',
                'iso_code2' =>  'SO',
                'iso_code3' =>  'SOM',
                'numeric'   => '706',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'South Africa',
                'iso_code2' =>  'ZA',
                'iso_code3' =>  'ZAF',
                'numeric'   => '710',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'South Georgia and the South Sandwich Islands',
                'iso_code2' =>  'GS',
                'iso_code3' =>  'SGS',
                'numeric'   => '239',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'South Sudan',
                'iso_code2' =>  'SS',
                'iso_code3' =>  'SSD',
                'numeric'   => '728',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Spain',
                'iso_code2' =>  'ES',
                'iso_code3' =>  'ESP',
                'numeric'   => '724',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sri Lanka',
                'iso_code2' =>  'LK',
                'iso_code3' =>  'LKA',
                'numeric'   => '144',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sudan (the)',
                'iso_code2' =>  'SD',
                'iso_code3' =>  'SDN',
                'numeric'   => '729',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Suriname',
                'iso_code2' =>  'SR',
                'iso_code3' =>  'SUR',
                'numeric'   => '740',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Svalbard and Jan Mayen',
                'iso_code2' =>  'SJ',
                'iso_code3' =>  'SJM',
                'numeric'   => '744',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Sweden',
                'iso_code2' =>  'SE',
                'iso_code3' =>  'SWE',
                'numeric'   => '752',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Switzerland',
                'iso_code2' =>  'CH',
                'iso_code3' =>  'CHE',
                'numeric'   => '756',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Syrian Arab Republic',
                'iso_code2' =>  'SY',
                'iso_code3' =>  'SYR',
                'numeric'   => '760',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Taiwan (Province of China)',
                'iso_code2' =>  'TW',
                'iso_code3' =>  'TWN',
                'numeric'   => '158',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tajikistan',
                'iso_code2' =>  'TJ',
                'iso_code3' =>  'TJK',
                'numeric'   => '762',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tanzania, United Republic of',
                'iso_code2' =>  'TZ',
                'iso_code3' =>  'TZA',
                'numeric'   => '834',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Thailand',
                'iso_code2' =>  'TH',
                'iso_code3' =>  'THA',
                'numeric'   => '764',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Timor-Leste',
                'iso_code2' =>  'TL',
                'iso_code3' =>  'TLS',
                'numeric'   => '626',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Togo',
                'iso_code2' =>  'TG',
                'iso_code3' =>  'TGO',
                'numeric'   => '768',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tokelau',
                'iso_code2' =>  'TK',
                'iso_code3' =>  'TKL',
                'numeric'   => '772',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tonga',
                'iso_code2' =>  'TO',
                'iso_code3' =>  'TON',
                'numeric'   => '776',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Trinidad and Tobago',
                'iso_code2' =>  'TT',
                'iso_code3' =>  'TTO',
                'numeric'   => '780',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tunisia',
                'iso_code2' =>  'TN',
                'iso_code3' =>  'TUN',
                'numeric'   => '788',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Turkey',
                'iso_code2' =>  'TR',
                'iso_code3' =>  'TUR',
                'numeric'   => '792',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Turkmenistan',
                'iso_code2' =>  'TM',
                'iso_code3' =>  'TKM',
                'numeric'   => '795',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Turks and Caicos Islands (the)',
                'iso_code2' =>  'TC',
                'iso_code3' =>  'TCA',
                'numeric'   => '796',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Tuvalu',
                'iso_code2' =>  'TV',
                'iso_code3' =>  'TUV',
                'numeric'   => '798',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Uganda',
                'iso_code2' =>  'UG',
                'iso_code3' =>  'UGA',
                'numeric'   => '800',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Ukraine',
                'iso_code2' =>  'UA',
                'iso_code3' =>  'UKR',
                'numeric'   => '804',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'United Arab Emirates (the)',
                'iso_code2' =>  'AE',
                'iso_code3' =>  'ARE',
                'numeric'   => '784',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'United Kingdom of Great Britain and Northern Ireland (the)',
                'iso_code2' =>  'GB',
                'iso_code3' =>  'GBR',
                'numeric'   => '826',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'United States Minor Outlying Islands (the)',
                'iso_code2' =>  'UM',
                'iso_code3' =>  'UMI',
                'numeric'   => '581',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'United States of America (the)',
                'iso_code2' =>  'US',
                'iso_code3' =>  'USA',
                'numeric'   => '840',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Uruguay',
                'iso_code2' =>  'UY',
                'iso_code3' =>  'URY',
                'numeric'   => '858',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Uzbekistan',
                'iso_code2' =>  'UZ',
                'iso_code3' =>  'UZB',
                'numeric'   => '860',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Vanuatu',
                'iso_code2' =>  'VU',
                'iso_code3' =>  'VUT',
                'numeric'   => '548',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Venezuela (Bolivarian Republic of)',
                'iso_code2' =>  'VE',
                'iso_code3' =>  'VEN',
                'numeric'   => '862',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Viet Nam',
                'iso_code2' =>  'VN',
                'iso_code3' =>  'VNM',
                'numeric'   => '704',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Virgin Islands (British)',
                'iso_code2' =>  'VG',
                'iso_code3' =>  'VGB',
                'numeric'   => '092',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Virgin Islands (U.S.)',
                'iso_code2' =>  'VI',
                'iso_code3' =>  'VIR',
                'numeric'   => '850',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Wallis and Futuna',
                'iso_code2' =>  'WF',
                'iso_code3' =>  'WLF',
                'numeric'   => '876',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Western Sahara',
                'iso_code2' =>  'EH',
                'iso_code3' =>  'ESH',
                'numeric'   => '732',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Yemen',
                'iso_code2' =>  'YE',
                'iso_code3' =>  'YEM',
                'numeric'   => '887',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Zambia',
                'iso_code2' =>  'ZM',
                'iso_code3' =>  'ZMB',
                'numeric'   => '894',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Zimbabwe',
                'iso_code2' =>  'ZW',
                'iso_code3' =>  'ZWE',
                'numeric'   => '716',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name'      =>  'Åland Islands',
                'iso_code2' =>  'AX',
                'iso_code3' =>  'ALA',
                'numeric'   => '248',
                'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
