<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UserMeasurementProfileValueTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_measurement_profile_values')->insert([
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  1,
        		'value'			=>	14.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  2,
        		'value'			=>	16.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  3,
        		'value'			=>	27.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  4,
        		'value'			=>	27.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  5,
        		'value'			=>	22.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  6,
        		'value'			=>	32.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  7,
        		'value'			=>	28.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  8,
        		'value'			=>	35.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  9,
        		'value'			=>	8.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  10,
        		'value'			=>	8.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  1,
        		'm_at_id'   	=>  11,
        		'value'			=>	8.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  1,
        		'value'			=>	15.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  2,
        		'value'			=>	17.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  3,
        		'value'			=>	28.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  4,
        		'value'			=>	28.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  5,
        		'value'			=>	23.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  6,
        		'value'			=>	34.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  7,
        		'value'			=>	30.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  8,
        		'value'			=>	36.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  9,
        		'value'			=>	9.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  10,
        		'value'			=>	9.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  2,
        		'm_at_id'   	=>  11,
        		'value'			=>	9.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  1,
        		'value'			=>	16.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  2,
        		'value'			=>	17.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  3,
        		'value'			=>	28.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  4,
        		'value'			=>	28.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  5,
        		'value'			=>	23.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  6,
        		'value'			=>	36.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  7,
        		'value'			=>	32.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  8,
        		'value'			=>	38.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  9,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  10,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  3,
        		'm_at_id'   	=>  11,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  1,
        		'value'			=>	16.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  2,
        		'value'			=>	18.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  3,
        		'value'			=>	29.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  4,
        		'value'			=>	29.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  5,
        		'value'			=>	23.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  6,
        		'value'			=>	38.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  7,
        		'value'			=>	35.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  8,
        		'value'			=>	40.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  9,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  10,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  4,
        		'm_at_id'   	=>  11,
        		'value'			=>	9.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  1,
        		'value'			=>	17.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  2,
        		'value'			=>	18.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  3,
        		'value'			=>	29.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  4,
        		'value'			=>	29.50,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  5,
        		'value'			=>	24.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  6,
        		'value'			=>	40.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  7,
        		'value'			=>	37.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  8,
        		'value'			=>	41.00,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  9,
        		'value'			=>	9.75,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  10,
        		'value'			=>	9.75,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	],
        	[
        		'u_mp_id'		=>  5,
        		'm_at_id'   	=>  11,
        		'value'			=>	9.75,
        		'created_at' 	=> Carbon::now(),
	            'updated_at' 	=> Carbon::now(),
        	]
        ]);
    }
}
